<a href="https://colab.research.google.com/github/irene06/Implementation_of_CNNinpython/blob/main/Implementation_of_CNNinpython_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [21]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [22]:
(X_train,y_train),(X_test,y_test)= mnist.load_data()


In [26]:
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], X_train.shape[2], 1))

In [27]:
X_test = X_test.reshape((X_test.shape[0],X_test.shape[1],X_test.shape[2],1))

In [29]:
print(X_train.shape)

(60000, 28, 28, 1)


In [30]:
print(X_test.shape)

(10000, 28, 28, 1)


In [31]:
X_train=X_train/255

In [32]:
X_test=X_test/255

In [34]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [35]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [36]:
model = Sequential()

In [37]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))

In [38]:
model.add(MaxPool2D(2,2))

In [39]:
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [40]:
#adding output layer
model.add(Dense(10,activation='softmax'))

In [42]:
#compiling the model
model.compile(loss="sparse_categorical_crossentropy",optimizer='adam',metrics=['accuracy'])

In [43]:
#fitting the model
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.1552 - accuracy: 0.9530
Epoch 2/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0550 - accuracy: 0.9828
Epoch 3/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0358 - accuracy: 0.9886
Epoch 4/10
1875/1875 [==============================] - 39s 21ms/step - loss: 0.0239 - accuracy: 0.9925
Epoch 5/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0163 - accuracy: 0.9951
Epoch 6/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0119 - accuracy: 0.9962
Epoch 7/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0084 - accuracy: 0.9974
Epoch 8/10
1875/1875 [==============================] - 38s 20ms/step - loss: 0.0088 - accuracy: 0.9970
Epoch 9/10
1875/1875 [==============================] - 39s 21ms/step - loss: 0.0055 - accuracy: 0.9983
Epoch 10/10
1875/1875 [==============================] - 38s 20m

In [44]:
#evaluating the model
model.evaluate(X_test,y_test)

313/313 [==============================] - 3s 8ms/step - loss: 0.0594 - accuracy: 0.9867


[0.059425245970487595, 0.9866999983787537]